### ISSUE TITLE
Messages do not get delivered when using spring-boot-devtools

### ISSUE THREAD

**Issue by adam-arold** [Riptide/riptide.core.java#1]
I get the following error:

```
org.codetome.riptide.core.api.exception.MissingOperationException: Can't find consumer/processor for Message with group: RT_DEFAULT_GROUP, version: RT_DEFAULT_VERSION and class: class org.codetome.riptide.example.doc.protobuf.model.data.StoredHtmlDocumentData
        at org.codetome.riptide.core.adapter.rabbit.RabbitMessagingAdapter.fetchOperationFor(RabbitMessagingAdapter.kt:108)
        at org.codetome.riptide.core.adapter.rabbit.RabbitMessagingAdapter$subscribe$consumer$1.handleDelivery(RabbitMessagingAdapter.kt:88)
        at com.rabbitmq.client.impl.ConsumerDispatcher$5.run(ConsumerDispatcher.java:149)
        at com.rabbitmq.client.impl.ConsumerWorkService$WorkPoolRunnable.run(ConsumerWorkService.java:100)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by adam-arold** [comment]
The problem was that `spring-boot-devtools` reloads classes with a different classloader so the class loaded based on the `Message` being delivered was not of the same class as the one known by the app. Issue fixed by using the context class loader instead of `Class.forName`
